language: node_js
cache:
  directories:
    - node_modules
    - $HOME/.yarn-cache
notifications:
  email: false
node_js:
  - '7'
before_install:
  - npm i -g npm@^5.0.0
script:
  - npm run validate
after_success:
  - npm run semantic-release
  - npm run report-coverage
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
